// basic
TXT_LABEL=label,
BTN_CMD=cmd,
BTN_LABEL=label,
IS_CONSEC=isConsec,
DISABLE_KEYBOARD_HIDDEN=disableKeyboardHidden,
LIST_PATH=listPath,
LIMIT_NUM=limitNum,
SELECT_JS_PATH=selectJsPath,


// setting
NOTIFICATION_CHANNEL_NUM=23,
PORT_NUM=10201,
URL_LAUNCH_ACTION_NAME=
	"com.puutaro.commandclick.url.launch",
SET_BLANK_MARK=
	"BLANK",

// fannel file path
FANNEL_PATH=
	"${0}",
FANNEL_NAME=
	"${02}",

// dir path
CURRENT_APP_DIR_PATH=
	"${01}",
FILE_MANAGER_DIR_PATH=
	"${CURRENT_APP_DIR_PATH}/${001}",
FILE_MANAGE_SHELL_DIR_PATH=
	"${FILE_MANAGER_DIR_PATH}/shell",
FILE_MANAGER_NOTIFICATION_DIR_PATH=
	"${FILE_MANAGE_SHELL_DIR_PATH}/notification",
FILE_MANAGER_TEMP_DIR_PATH=
	"${FILE_MANAGER_DIR_PATH}/temp",
FILE_MANAGER_LIST_DIR_PATH=
	"${FILE_MANAGER_DIR_PATH}/list",
FILE_MANAGER_SELECT_SCRIPT_DIR_PATH=
	"${FILE_MANAGER_DIR_PATH}/select",
FILE_MANAGER_SYSTEM_JS_DIR_PATH=
	"${FILE_MANAGER_DIR_PATH}/systemJs",
FILE_MANAGER_JS_DIR_PATH=
	"${FILE_MANAGER_DIR_PATH}/js",
FILE_MANAGER_LIBS_DIR_PATH=
	"${FILE_MANAGER_DIR_PATH}/libs",


// js file path
FILE_MANAGER_REGISTER_DIR_PATH_JS_PATH=
	"${FILE_MANAGER_JS_DIR_PATH}/registerDirPath.js",
FILE_MANAGER_SELECT_DIR_PATH_JS_PATH=
	"${FILE_MANAGER_SELECT_SCRIPT_DIR_PATH}/selectDirPath.js",
FILE_MANAGER_SELECT_DIR_DIALOG_JS_PATH=
	"${FILE_MANAGER_JS_DIR_PATH}/selectDirDialog.js",
FILE_MANAGER_COPY_JS_PATH=
	"${FILE_MANAGER_JS_DIR_PATH}/copy.js",
FILE_MANAGER_SETTING_JS_PATH=
	"${FILE_MANAGER_JS_DIR_PATH}/setting.js",

// js libs
FILE_MANAGER_BROWSE_JS_PATH=
	"${FILE_MANAGER_LIBS_DIR_PATH}/browse.js",
FILE_MANAGER_BROWSE_HANDLER_JS_PATH=
	"${FILE_MANAGER_LIBS_DIR_PATH}/browseHandler.js",
UPDATE_LIST_BOX_JS__PATH=
	"${FILE_MANAGER_LIBS_DIR_PATH}/updateListBox.js",
READ_CMD_VAL_JS_PATH=
	"${FILE_MANAGER_LIBS_DIR_PATH}/readCmdVal.js",
FILE_MANAGER_DIR_PATH_JS_PATH=
	"${FILE_MANAGER_LIBS_DIR_PATH}/dirPath.js",

// shell path
FILE_MANAGER_BROWSE_SHELL_PATH=
	"${FILE_MANAGE_SHELL_DIR_PATH}/browse.sh",
FILE_MANAGER_INSTALL_SHELL_PATH=
	"${FILE_MANAGE_SHELL_DIR_PATH}/install.sh",

// notification
NOTI_LAUNCH_SHELL_PATH=
	"${FILE_MANAGER_NOTIFICATION_DIR_PATH}/launch.sh",
NOTI_EXIT_SHELL_PATH=
	"${FILE_MANAGER_NOTIFICATION_DIR_PATH}/exit.sh",

// other file
FILE_MANAGER_DIR_LIST_TXT_PATH=
	"${FILE_MANAGER_LIST_DIR_PATH}/dirPathList.txt",
FILE_MANAGER_ROOT_DIR_LIST_TXT_PATH=
	"${FILE_MANAGER_LIST_DIR_PATH}/rootDirPathList.txt",
FILE_MANAGER_BASE_URL_LIST_TXT_PATH=
	"${FILE_MANAGER_LIST_DIR_PATH}/baseUrlList.txt",
FILE_MANAGE_ARGS_TSV_PATH=
	"${FILE_MANAGER_TEMP_DIR_PATH}/args.tsv",
PRVIOUS_ROOT_DIR_MEMO_TXT_PATH=
	"${FILE_MANAGER_TEMP_DIR_PATH}/previous_root_dir.txt",