
// basic
TXT_LABEL=label,
BTN_CMD=cmd,
BTN_LABEL=label,
LIST_PATH=listPath,
LIMIT_NUM=limitNum,
CSV_SUFFIX=".csv",
TSV_SUFFIX=".tsv",

// path
PARRENT_APP_DIR_PATH=
	"${01}",
CURRENT_APP_DIR_PATH=
	"${PARRENT_APP_DIR_PATH}/${001}",
CURRENT_LIST_DIR_PATH=
	"${CURRENT_APP_DIR_PATH}/list",
CURRENT_COLUMN_LIST_FILE_PATH=
	"${CURRENT_LIST_DIR_PATH}/columnList",
CURRENT_FILTERS_LIST_FILE_PATH=
	"${CURRENT_LIST_DIR_PATH}/filtersList",
CURRENT_FILTER_GAIN_LIST_FILE_PATH=
	"${CURRENT_LIST_DIR_PATH}/filterGainList",
CURRENT_INUPT_CSV_LIST_FILE_PATH=
	"${CURRENT_LIST_DIR_PATH}/inuptCsvList",