

LAUNCH_URL:
	TXT:ELSB=
		${LIST_PATH}=${URL_LIST_FILE_PATH}
			!${SELECT_JS}=${LAUNCH_URL_SELECTED_JS_PATH},

REMOVE_LAUNCH_URL:
	TXT:ELSB:BTN=
		${LIST_PATH}=${URL_LIST_FILE_PATH}
		|
			${BTN_CMD}=jsf '${0}' REMOVE_LAUNCH_URL
			!${BTN_LABEL}=del
