editExecute,
onUpdateLastModify,
onAdBlock,
setReplaceVariables,
setVariableTypes,
playButtonConfig,
editButtonConfig,
settingButtonConfig,
hideSettingVariables,
fannelStateConfig,

appHeader,
table,
manager,
extraButton,
playBtns,
playMode,