// basic
TXT_LABEL=label,
BTN_CMD=cmd,
BTN_LABEL=label,
LIST_PATH=listPath,
LIMIT_NUM=limitNum,

// path
NEWS_APP_DIR_PATH=
	"${01}/${001}",
NEWS_APP_LIST_DIR_PATH=
	"${NEWS_APP_DIR_PATH}/list",
WEB_SEARCH_PREFIX_FILE_PATH=
	"${NEWS_APP_LIST_DIR_PATH}/webSearchPrefixList",
GGLE_SEARCH_LIST_FILE_PATH=
	"${NEWS_APP_LIST_DIR_PATH}/ggleSearchList",
SEARCH_LIST_FILE_PATH=
	"${NEWS_APP_LIST_DIR_PATH}/searchList",
SEARCH_JS_DIR_PATH=
	"${NEWS_APP_DIR_PATH}/js",
CP_SEARCH_JS_PATH=
	"${SEARCH_JS_DIR_PATH}/cpSearch.js",