
WEB_SEARCH_PREFIX:
	LBL:TXT:ELSB=
		${TXT_LABEL}=THIS
		|
			${LIST_PATH}=${WEB_SEARCH_PREFIX_FILE_PATH}
				!${limitNum}=30,
REMOVE_WEB_SEARCH_PREFIX:
	LBL:TXT:ELSB:BTN=
		${TXT_LABEL}=THIS
		|
			${LIST_PATH}=${WEB_SEARCH_PREFIX_FILE_PATH}
		|
			${BTN_CMD}=jsf '${0}' remove_web_search_prefix
				!${BTN_LABEL}=del,
SEARCH_TEXT:
	LBL:TXT:ELSB=
		${TXT_LABEL}=THIS
		|
			${LIST_PATH}=${SEARCH_LIST_FILE_PATH}
				!${limitNum}=30,
REMOVE_SEARCH_TEXT:
	LBL:TXT:ELSB:BTN=
		${TXT_LABEL}=THIS
		|
			${LIST_PATH}=${SEARCH_LIST_FILE_PATH}
		|
			${BTN_CMD}=jsf '${0}' remove_search_text
				!${BTN_LABEL}=del,
GGLE_SEARCH_TEXT:
	LBL:TXT:ELSB=
		${TXT_LABEL}=THIS
		|
			${LIST_PATH}=${GGLE_SEARCH_LIST_FILE_PATH}
				!${limitNum}=10,
GGLE_SEARCH:
	BTN:HL=
		cmd=jsf '${0}' GGLE_SEARCH
			!${BTN_LABEL}=this,
