editExecute,
onAutoExec,
onAdBlock,
onTermBackendWhenStart,
onTermVisibleWhenKeyboard,
onTermShortWhenLoad,
onUrlHistoryRegister,
defaultMonitorFile,
terminalFontZoom,
setReplaceVariables,
setVariableTypes,
description,

