name: create fannel list
on: 
  workflow_dispatch:
  schedule:
    - cron: '13 15 * * *'
jobs:
  echo-fannel-list-update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "exec fannel list update"

  exec-create:
    needs: echo-fannel-list-update
    if: ${{ needs.changes.outputs.fannels == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # 書き込むために必要
    steps:
      - uses: actions/checkout@v3
      - run: bash "manage/fannels/create_fannel_list.sh"
      - uses: stefanzweifel/git-auto-commit-action@v4
