name: create fannel list
on: 
  workflow_dispatch:
jobs:
  exec-pwd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash -c "pwd;ls"
      #- uses: stefanzweifel/git-auto-commit-action@v4

  changes:
    runs-on: ubuntu-latest
    outputs:
      fannels: ${{ steps.filter.outputs.fannels }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          fannels:
            - 'fannel/**'

  exec-create:
    needs: changes
    if: ${{ needs.changes.outputs.fannels == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # 書き込むために必要
    steps:
      - uses: actions/checkout@v3
      - run: bash "manage/fannels/create_fannel_list.sh"
      - uses: stefanzweifel/git-auto-commit-action@v4
