name: update fannel repository
on: 
  workflow_dispatch:
  schedule:
    - cron: '20 20 * * *'
jobs:
  update-fannel-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 書き込むために必要
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push from register fannel repos
        run: |
          bash "manage/fannels/push_other_fannel_repo_con.sh"
      - name: Update fannel list
        run: |
          bash "manage/fannels/update_fannel_list.sh"
      - name: Make fannel tar gz
        run: |
          bash "manage/fannels/make_fannel_tar_gz.sh"
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5

